// <auto-generated />
using System;
using CondominioAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CondominioAPI.Migrations
{
    [DbContext(typeof(CondominioDbContext))]
    [Migration("20210615223116_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CondominioAPI.Data.Entities.AlquilerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ArrendatarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DepartamentoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArrendatarioId");

                    b.HasIndex("DepartamentoId")
                        .IsUnique()
                        .HasFilter("[DepartamentoId] IS NOT NULL");

                    b.ToTable("Alquileres");
                });

            modelBuilder.Entity("CondominioAPI.Data.Entities.DepartamentoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bloque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroDepartamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDormitorios")
                        .HasColumnType("int");

                    b.Property<long?>("PropietarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PropietarioId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("CondominioAPI.Data.Entities.PersonaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Celular")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<long>("Identificacion")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Residentes");
                });

            modelBuilder.Entity("CondominioAPI.Data.Entities.AlquilerEntity", b =>
                {
                    b.HasOne("CondominioAPI.Data.Entities.PersonaEntity", "Arrendatario")
                        .WithMany("Alquileres")
                        .HasForeignKey("ArrendatarioId");

                    b.HasOne("CondominioAPI.Data.Entities.DepartamentoEntity", "Departamento")
                        .WithOne("Alquiler")
                        .HasForeignKey("CondominioAPI.Data.Entities.AlquilerEntity", "DepartamentoId");
                });

            modelBuilder.Entity("CondominioAPI.Data.Entities.DepartamentoEntity", b =>
                {
                    b.HasOne("CondominioAPI.Data.Entities.PersonaEntity", "Propietario")
                        .WithMany("Departamentos")
                        .HasForeignKey("PropietarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
